//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Bluedot.HabboServer.Database", "habbos_ibfk_1", "DBLogin", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Bluedot.HabboServer.Database.DBLogin), "DBHabbo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Bluedot.HabboServer.Database.DBHabbo), true)]
[assembly: EdmRelationshipAttribute("Bluedot.HabboServer.Database", "messenger_categories_ibfk_1", "DBHabbo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Bluedot.HabboServer.Database.DBHabbo), "DBMessengerCategory", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Bluedot.HabboServer.Database.DBMessengerCategory), true)]
[assembly: EdmRelationshipAttribute("Bluedot.HabboServer.Database", "messenger_friend_requests_ibfk_1", "DBHabbo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Bluedot.HabboServer.Database.DBHabbo), "DBMessengerFriendRequest", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Bluedot.HabboServer.Database.DBMessengerFriendRequest), true)]
[assembly: EdmRelationshipAttribute("Bluedot.HabboServer.Database", "messenger_friend_requests_ibfk_2", "DBHabbo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Bluedot.HabboServer.Database.DBHabbo), "DBMessengerFriendRequest", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Bluedot.HabboServer.Database.DBMessengerFriendRequest), true)]
[assembly: EdmRelationshipAttribute("Bluedot.HabboServer.Database", "messenger_friendships_ibfk_1", "DBHabbo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Bluedot.HabboServer.Database.DBHabbo), "DBMessengerFriendship", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Bluedot.HabboServer.Database.DBMessengerFriendship), true)]
[assembly: EdmRelationshipAttribute("Bluedot.HabboServer.Database", "messenger_friendships_ibfk_3", "DBHabbo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Bluedot.HabboServer.Database.DBHabbo), "DBMessengerFriendship", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Bluedot.HabboServer.Database.DBMessengerFriendship), true)]
[assembly: EdmRelationshipAttribute("Bluedot.HabboServer.Database", "rooms_ibfk_1", "DBHabbo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Bluedot.HabboServer.Database.DBHabbo), "DBRoom", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Bluedot.HabboServer.Database.DBRoom), true)]
[assembly: EdmRelationshipAttribute("Bluedot.HabboServer.Database", "subscriptions_ibfk_1", "DBHabbo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Bluedot.HabboServer.Database.DBHabbo), "DBSubscription", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Bluedot.HabboServer.Database.DBSubscription), true)]
[assembly: EdmRelationshipAttribute("Bluedot.HabboServer.Database", "messenger_friendships_ibfk_2", "DBMessengerCategory", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Bluedot.HabboServer.Database.DBMessengerCategory), "DBMessengerFriendship", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Bluedot.HabboServer.Database.DBMessengerFriendship), true)]
[assembly: EdmRelationshipAttribute("Bluedot.HabboServer.Database", "messenger_friendships_ibfk_4", "DBMessengerCategory", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Bluedot.HabboServer.Database.DBMessengerCategory), "DBMessengerFriendship", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Bluedot.HabboServer.Database.DBMessengerFriendship), true)]

#endregion

namespace Bluedot.HabboServer.Database
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Session : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Session object using the connection string found in the 'Session' section of the application configuration file.
        /// </summary>
        public Session() : base("name=Session", "Session")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Session object.
        /// </summary>
        public Session(string connectionString) : base(connectionString, "Session")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Session object.
        /// </summary>
        public Session(EntityConnection connection) : base(connection, "Session")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DBHabbo> Habbos
        {
            get
            {
                if ((_Habbos == null))
                {
                    _Habbos = base.CreateObjectSet<DBHabbo>("Habbos");
                }
                return _Habbos;
            }
        }
        private ObjectSet<DBHabbo> _Habbos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DBLogin> Logins
        {
            get
            {
                if ((_Logins == null))
                {
                    _Logins = base.CreateObjectSet<DBLogin>("Logins");
                }
                return _Logins;
            }
        }
        private ObjectSet<DBLogin> _Logins;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DBMessengerCategory> MessengerCategories
        {
            get
            {
                if ((_MessengerCategories == null))
                {
                    _MessengerCategories = base.CreateObjectSet<DBMessengerCategory>("MessengerCategories");
                }
                return _MessengerCategories;
            }
        }
        private ObjectSet<DBMessengerCategory> _MessengerCategories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DBMessengerFriendRequest> MessengerFriendRequests
        {
            get
            {
                if ((_MessengerFriendRequests == null))
                {
                    _MessengerFriendRequests = base.CreateObjectSet<DBMessengerFriendRequest>("MessengerFriendRequests");
                }
                return _MessengerFriendRequests;
            }
        }
        private ObjectSet<DBMessengerFriendRequest> _MessengerFriendRequests;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DBMessengerFriendship> MessengerFriendships
        {
            get
            {
                if ((_MessengerFriendships == null))
                {
                    _MessengerFriendships = base.CreateObjectSet<DBMessengerFriendship>("MessengerFriendships");
                }
                return _MessengerFriendships;
            }
        }
        private ObjectSet<DBMessengerFriendship> _MessengerFriendships;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DBRoom> Rooms
        {
            get
            {
                if ((_Rooms == null))
                {
                    _Rooms = base.CreateObjectSet<DBRoom>("Rooms");
                }
                return _Rooms;
            }
        }
        private ObjectSet<DBRoom> _Rooms;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DBSubscription> Subscriptions
        {
            get
            {
                if ((_Subscriptions == null))
                {
                    _Subscriptions = base.CreateObjectSet<DBSubscription>("Subscriptions");
                }
                return _Subscriptions;
            }
        }
        private ObjectSet<DBSubscription> _Subscriptions;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Habbos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHabbos(DBHabbo dBHabbo)
        {
            base.AddObject("Habbos", dBHabbo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Logins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLogins(DBLogin dBLogin)
        {
            base.AddObject("Logins", dBLogin);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MessengerCategories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMessengerCategories(DBMessengerCategory dBMessengerCategory)
        {
            base.AddObject("MessengerCategories", dBMessengerCategory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MessengerFriendRequests EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMessengerFriendRequests(DBMessengerFriendRequest dBMessengerFriendRequest)
        {
            base.AddObject("MessengerFriendRequests", dBMessengerFriendRequest);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MessengerFriendships EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMessengerFriendships(DBMessengerFriendship dBMessengerFriendship)
        {
            base.AddObject("MessengerFriendships", dBMessengerFriendship);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Rooms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRooms(DBRoom dBRoom)
        {
            base.AddObject("Rooms", dBRoom);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Subscriptions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSubscriptions(DBSubscription dBSubscription)
        {
            base.AddObject("Subscriptions", dBSubscription);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Bluedot.HabboServer.Database", Name="DBHabbo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DBHabbo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DBHabbo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="loginId">Initial value of the LoginId property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="dateCreated">Initial value of the DateCreated property.</param>
        /// <param name="figureString">Initial value of the FigureString property.</param>
        /// <param name="rawSwimColour">Initial value of the RawSwimColour property.</param>
        /// <param name="figureGender">Initial value of the FigureGender property.</param>
        /// <param name="motto">Initial value of the Motto property.</param>
        /// <param name="credits">Initial value of the Credits property.</param>
        /// <param name="pixels">Initial value of the Pixels property.</param>
        public static DBHabbo CreateDBHabbo(global::System.Int32 id, global::System.Int32 loginId, global::System.String username, global::System.DateTime dateCreated, global::System.String figureString, global::System.Int32 rawSwimColour, global::System.Boolean figureGender, global::System.String motto, global::System.Int32 credits, global::System.Int32 pixels)
        {
            DBHabbo dBHabbo = new DBHabbo();
            dBHabbo.Id = id;
            dBHabbo.LoginId = loginId;
            dBHabbo.Username = username;
            dBHabbo.DateCreated = dateCreated;
            dBHabbo.FigureString = figureString;
            dBHabbo.RawSwimColour = rawSwimColour;
            dBHabbo.FigureGender = figureGender;
            dBHabbo.Motto = motto;
            dBHabbo.Credits = credits;
            dBHabbo.Pixels = pixels;
            return dBHabbo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LoginId
        {
            get
            {
                return _LoginId;
            }
            set
            {
                OnLoginIdChanging(value);
                ReportPropertyChanging("LoginId");
                _LoginId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LoginId");
                OnLoginIdChanged();
            }
        }
        private global::System.Int32 _LoginId;
        partial void OnLoginIdChanging(global::System.Int32 value);
        partial void OnLoginIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FigureString
        {
            get
            {
                return _FigureString;
            }
            set
            {
                OnFigureStringChanging(value);
                ReportPropertyChanging("FigureString");
                _FigureString = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FigureString");
                OnFigureStringChanged();
            }
        }
        private global::System.String _FigureString;
        partial void OnFigureStringChanging(global::System.String value);
        partial void OnFigureStringChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RawSwimColour
        {
            get
            {
                return _RawSwimColour;
            }
            set
            {
                OnRawSwimColourChanging(value);
                ReportPropertyChanging("RawSwimColour");
                _RawSwimColour = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RawSwimColour");
                OnRawSwimColourChanged();
            }
        }
        private global::System.Int32 _RawSwimColour;
        partial void OnRawSwimColourChanging(global::System.Int32 value);
        partial void OnRawSwimColourChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean FigureGender
        {
            get
            {
                return _FigureGender;
            }
            set
            {
                OnFigureGenderChanging(value);
                ReportPropertyChanging("FigureGender");
                _FigureGender = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FigureGender");
                OnFigureGenderChanged();
            }
        }
        private global::System.Boolean _FigureGender;
        partial void OnFigureGenderChanging(global::System.Boolean value);
        partial void OnFigureGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Motto
        {
            get
            {
                return _Motto;
            }
            set
            {
                OnMottoChanging(value);
                ReportPropertyChanging("Motto");
                _Motto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Motto");
                OnMottoChanged();
            }
        }
        private global::System.String _Motto;
        partial void OnMottoChanging(global::System.String value);
        partial void OnMottoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Credits
        {
            get
            {
                return _Credits;
            }
            set
            {
                OnCreditsChanging(value);
                ReportPropertyChanging("Credits");
                _Credits = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Credits");
                OnCreditsChanged();
            }
        }
        private global::System.Int32 _Credits;
        partial void OnCreditsChanging(global::System.Int32 value);
        partial void OnCreditsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Pixels
        {
            get
            {
                return _Pixels;
            }
            set
            {
                OnPixelsChanging(value);
                ReportPropertyChanging("Pixels");
                _Pixels = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pixels");
                OnPixelsChanged();
            }
        }
        private global::System.Int32 _Pixels;
        partial void OnPixelsChanging(global::System.Int32 value);
        partial void OnPixelsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastAccess
        {
            get
            {
                return _LastAccess;
            }
            set
            {
                OnLastAccessChanging(value);
                ReportPropertyChanging("LastAccess");
                _LastAccess = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastAccess");
                OnLastAccessChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastAccess;
        partial void OnLastAccessChanging(Nullable<global::System.DateTime> value);
        partial void OnLastAccessChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SSOTicket
        {
            get
            {
                return _SSOTicket;
            }
            set
            {
                OnSSOTicketChanging(value);
                ReportPropertyChanging("SSOTicket");
                _SSOTicket = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SSOTicket");
                OnSSOTicketChanged();
            }
        }
        private global::System.String _SSOTicket;
        partial void OnSSOTicketChanging(global::System.String value);
        partial void OnSSOTicketChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] RawOriginIP
        {
            get
            {
                return StructuralObject.GetValidValue(_RawOriginIP);
            }
            set
            {
                OnRawOriginIPChanging(value);
                ReportPropertyChanging("RawOriginIP");
                _RawOriginIP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RawOriginIP");
                OnRawOriginIPChanged();
            }
        }
        private global::System.Byte[] _RawOriginIP;
        partial void OnRawOriginIPChanging(global::System.Byte[] value);
        partial void OnRawOriginIPChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Bluedot.HabboServer.Database", Name="DBLogin")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DBLogin : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DBLogin object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="dateOfBirth">Initial value of the DateOfBirth property.</param>
        /// <param name="datedCreated">Initial value of the DatedCreated property.</param>
        public static DBLogin CreateDBLogin(global::System.Int32 id, global::System.String email, global::System.String password, global::System.DateTime dateOfBirth, global::System.DateTime datedCreated)
        {
            DBLogin dBLogin = new DBLogin();
            dBLogin.Id = id;
            dBLogin.Email = email;
            dBLogin.Password = password;
            dBLogin.DateOfBirth = dateOfBirth;
            dBLogin.DatedCreated = datedCreated;
            return dBLogin;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateOfBirth
        {
            get
            {
                return _DateOfBirth;
            }
            set
            {
                OnDateOfBirthChanging(value);
                ReportPropertyChanging("DateOfBirth");
                _DateOfBirth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfBirth");
                OnDateOfBirthChanged();
            }
        }
        private global::System.DateTime _DateOfBirth;
        partial void OnDateOfBirthChanging(global::System.DateTime value);
        partial void OnDateOfBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DatedCreated
        {
            get
            {
                return _DatedCreated;
            }
            set
            {
                OnDatedCreatedChanging(value);
                ReportPropertyChanging("DatedCreated");
                _DatedCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DatedCreated");
                OnDatedCreatedChanged();
            }
        }
        private global::System.DateTime _DatedCreated;
        partial void OnDatedCreatedChanging(global::System.DateTime value);
        partial void OnDatedCreatedChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Bluedot.HabboServer.Database", Name="DBMessengerCategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DBMessengerCategory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DBMessengerCategory object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="ownerId">Initial value of the OwnerId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static DBMessengerCategory CreateDBMessengerCategory(global::System.Int32 id, global::System.Int32 ownerId, global::System.String name)
        {
            DBMessengerCategory dBMessengerCategory = new DBMessengerCategory();
            dBMessengerCategory.Id = id;
            dBMessengerCategory.OwnerId = ownerId;
            dBMessengerCategory.Name = name;
            return dBMessengerCategory;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OwnerId
        {
            get
            {
                return _OwnerId;
            }
            set
            {
                OnOwnerIdChanging(value);
                ReportPropertyChanging("OwnerId");
                _OwnerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OwnerId");
                OnOwnerIdChanged();
            }
        }
        private global::System.Int32 _OwnerId;
        partial void OnOwnerIdChanging(global::System.Int32 value);
        partial void OnOwnerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Bluedot.HabboServer.Database", "messenger_categories_ibfk_1", "DBHabbo")]
        public DBHabbo habbo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DBHabbo>("Bluedot.HabboServer.Database.messenger_categories_ibfk_1", "DBHabbo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DBHabbo>("Bluedot.HabboServer.Database.messenger_categories_ibfk_1", "DBHabbo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DBHabbo> habboReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DBHabbo>("Bluedot.HabboServer.Database.messenger_categories_ibfk_1", "DBHabbo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DBHabbo>("Bluedot.HabboServer.Database.messenger_categories_ibfk_1", "DBHabbo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Bluedot.HabboServer.Database", "messenger_friendships_ibfk_2", "DBMessengerFriendship")]
        public EntityCollection<DBMessengerFriendship> messenger_friendships
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DBMessengerFriendship>("Bluedot.HabboServer.Database.messenger_friendships_ibfk_2", "DBMessengerFriendship");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DBMessengerFriendship>("Bluedot.HabboServer.Database.messenger_friendships_ibfk_2", "DBMessengerFriendship", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Bluedot.HabboServer.Database", "messenger_friendships_ibfk_4", "DBMessengerFriendship")]
        public EntityCollection<DBMessengerFriendship> messenger_friendships1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DBMessengerFriendship>("Bluedot.HabboServer.Database.messenger_friendships_ibfk_4", "DBMessengerFriendship");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DBMessengerFriendship>("Bluedot.HabboServer.Database.messenger_friendships_ibfk_4", "DBMessengerFriendship", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Bluedot.HabboServer.Database", Name="DBMessengerFriendRequest")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DBMessengerFriendRequest : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DBMessengerFriendRequest object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="fromId">Initial value of the FromId property.</param>
        /// <param name="toId">Initial value of the ToId property.</param>
        public static DBMessengerFriendRequest CreateDBMessengerFriendRequest(global::System.Int32 id, global::System.Int32 fromId, global::System.Int32 toId)
        {
            DBMessengerFriendRequest dBMessengerFriendRequest = new DBMessengerFriendRequest();
            dBMessengerFriendRequest.Id = id;
            dBMessengerFriendRequest.FromId = fromId;
            dBMessengerFriendRequest.ToId = toId;
            return dBMessengerFriendRequest;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FromId
        {
            get
            {
                return _FromId;
            }
            set
            {
                OnFromIdChanging(value);
                ReportPropertyChanging("FromId");
                _FromId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FromId");
                OnFromIdChanged();
            }
        }
        private global::System.Int32 _FromId;
        partial void OnFromIdChanging(global::System.Int32 value);
        partial void OnFromIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ToId
        {
            get
            {
                return _ToId;
            }
            set
            {
                OnToIdChanging(value);
                ReportPropertyChanging("ToId");
                _ToId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ToId");
                OnToIdChanged();
            }
        }
        private global::System.Int32 _ToId;
        partial void OnToIdChanging(global::System.Int32 value);
        partial void OnToIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Bluedot.HabboServer.Database", Name="DBMessengerFriendship")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DBMessengerFriendship : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DBMessengerFriendship object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="habboAId">Initial value of the HabboAId property.</param>
        /// <param name="habboBId">Initial value of the HabboBId property.</param>
        public static DBMessengerFriendship CreateDBMessengerFriendship(global::System.Int32 id, global::System.Int32 habboAId, global::System.Int32 habboBId)
        {
            DBMessengerFriendship dBMessengerFriendship = new DBMessengerFriendship();
            dBMessengerFriendship.Id = id;
            dBMessengerFriendship.HabboAId = habboAId;
            dBMessengerFriendship.HabboBId = habboBId;
            return dBMessengerFriendship;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HabboAId
        {
            get
            {
                return _HabboAId;
            }
            set
            {
                OnHabboAIdChanging(value);
                ReportPropertyChanging("HabboAId");
                _HabboAId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HabboAId");
                OnHabboAIdChanged();
            }
        }
        private global::System.Int32 _HabboAId;
        partial void OnHabboAIdChanging(global::System.Int32 value);
        partial void OnHabboAIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CategoryAId
        {
            get
            {
                return _CategoryAId;
            }
            set
            {
                OnCategoryAIdChanging(value);
                ReportPropertyChanging("CategoryAId");
                _CategoryAId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoryAId");
                OnCategoryAIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CategoryAId;
        partial void OnCategoryAIdChanging(Nullable<global::System.Int32> value);
        partial void OnCategoryAIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HabboBId
        {
            get
            {
                return _HabboBId;
            }
            set
            {
                OnHabboBIdChanging(value);
                ReportPropertyChanging("HabboBId");
                _HabboBId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HabboBId");
                OnHabboBIdChanged();
            }
        }
        private global::System.Int32 _HabboBId;
        partial void OnHabboBIdChanging(global::System.Int32 value);
        partial void OnHabboBIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CategoryBId
        {
            get
            {
                return _CategoryBId;
            }
            set
            {
                OnCategoryBIdChanging(value);
                ReportPropertyChanging("CategoryBId");
                _CategoryBId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoryBId");
                OnCategoryBIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CategoryBId;
        partial void OnCategoryBIdChanging(Nullable<global::System.Int32> value);
        partial void OnCategoryBIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Bluedot.HabboServer.Database", Name="DBRoom")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DBRoom : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DBRoom object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="ownerId">Initial value of the OwnerId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="categoryId">Initial value of the CategoryId property.</param>
        /// <param name="lastEntry">Initial value of the LastEntry property.</param>
        public static DBRoom CreateDBRoom(global::System.Int32 id, global::System.Int32 ownerId, global::System.String name, global::System.String description, global::System.String categoryId, global::System.DateTime lastEntry)
        {
            DBRoom dBRoom = new DBRoom();
            dBRoom.Id = id;
            dBRoom.OwnerId = ownerId;
            dBRoom.Name = name;
            dBRoom.Description = description;
            dBRoom.CategoryId = categoryId;
            dBRoom.LastEntry = lastEntry;
            return dBRoom;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OwnerId
        {
            get
            {
                return _OwnerId;
            }
            set
            {
                OnOwnerIdChanging(value);
                ReportPropertyChanging("OwnerId");
                _OwnerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OwnerId");
                OnOwnerIdChanged();
            }
        }
        private global::System.Int32 _OwnerId;
        partial void OnOwnerIdChanging(global::System.Int32 value);
        partial void OnOwnerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CategoryId
        {
            get
            {
                return _CategoryId;
            }
            set
            {
                OnCategoryIdChanging(value);
                ReportPropertyChanging("CategoryId");
                _CategoryId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CategoryId");
                OnCategoryIdChanged();
            }
        }
        private global::System.String _CategoryId;
        partial void OnCategoryIdChanging(global::System.String value);
        partial void OnCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastEntry
        {
            get
            {
                return _LastEntry;
            }
            set
            {
                OnLastEntryChanging(value);
                ReportPropertyChanging("LastEntry");
                _LastEntry = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastEntry");
                OnLastEntryChanged();
            }
        }
        private global::System.DateTime _LastEntry;
        partial void OnLastEntryChanging(global::System.DateTime value);
        partial void OnLastEntryChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Bluedot.HabboServer.Database", Name="DBSubscription")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DBSubscription : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DBSubscription object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="subscriberId">Initial value of the SubscriberId property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="totalBought">Initial value of the TotalBought property.</param>
        /// <param name="lengthSkipped">Initial value of the LengthSkipped property.</param>
        /// <param name="pausedStart">Initial value of the PausedStart property.</param>
        public static DBSubscription CreateDBSubscription(global::System.Int32 id, global::System.Int32 subscriberId, global::System.String type, global::System.Int32 totalBought, global::System.Int32 lengthSkipped, global::System.Int32 pausedStart)
        {
            DBSubscription dBSubscription = new DBSubscription();
            dBSubscription.Id = id;
            dBSubscription.SubscriberId = subscriberId;
            dBSubscription.Type = type;
            dBSubscription.TotalBought = totalBought;
            dBSubscription.LengthSkipped = lengthSkipped;
            dBSubscription.PausedStart = pausedStart;
            return dBSubscription;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SubscriberId
        {
            get
            {
                return _SubscriberId;
            }
            set
            {
                OnSubscriberIdChanging(value);
                ReportPropertyChanging("SubscriberId");
                _SubscriberId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SubscriberId");
                OnSubscriberIdChanged();
            }
        }
        private global::System.Int32 _SubscriberId;
        partial void OnSubscriberIdChanging(global::System.Int32 value);
        partial void OnSubscriberIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TotalBought
        {
            get
            {
                return _TotalBought;
            }
            set
            {
                OnTotalBoughtChanging(value);
                ReportPropertyChanging("TotalBought");
                _TotalBought = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalBought");
                OnTotalBoughtChanged();
            }
        }
        private global::System.Int32 _TotalBought;
        partial void OnTotalBoughtChanging(global::System.Int32 value);
        partial void OnTotalBoughtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LengthSkipped
        {
            get
            {
                return _LengthSkipped;
            }
            set
            {
                OnLengthSkippedChanging(value);
                ReportPropertyChanging("LengthSkipped");
                _LengthSkipped = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LengthSkipped");
                OnLengthSkippedChanged();
            }
        }
        private global::System.Int32 _LengthSkipped;
        partial void OnLengthSkippedChanging(global::System.Int32 value);
        partial void OnLengthSkippedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PausedStart
        {
            get
            {
                return _PausedStart;
            }
            set
            {
                OnPausedStartChanging(value);
                ReportPropertyChanging("PausedStart");
                _PausedStart = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PausedStart");
                OnPausedStartChanged();
            }
        }
        private global::System.Int32 _PausedStart;
        partial void OnPausedStartChanging(global::System.Int32 value);
        partial void OnPausedStartChanged();

        #endregion
    
    }

    #endregion
    
}
